spring:
  server:
    servlet:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        show_sql: true
  profiles:
    active: ms
